name: CI
on: push
jobs:
  build:
    name: ${{ matrix.config.os }} Build
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
        - {
            name: "Windows Latest MSVC", 
            os: windows-latest,
            cc: "cl",
            cxx: "cl",
          }
        - {
            name: "Ubuntu Latest GCC", 
            os: ubuntu-latest,
            cc: "gcc", 
            cxx: "g++"
          }
        - {
            name: "macOS Latest Clang",
            os: macos-latest,
            cc: "clang", 
            cxx: "clang++"
          }
    steps:
      - uses: actions/checkout@master
      - run: cmake -v
      - uses: ashutoshvarma/action-cmake-build@master
        with:
          cc: ${{ matrix.config.cc }}
          cxx: ${{ matrix.config.cxx }}
      
